# Generated by Django 3.1 on 2020-08-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200821_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='w', max_length=10, verbose_name='Пол:'),
        ),
    ]
