# Generated by Django 3.1 on 2020-08-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('m', 'мужской'), ('w', 'женский'), ('o', 'нет')], default='o', max_length=2, verbose_name='Пол:'),
        ),
    ]
