# Generated by Django 3.1 on 2020-08-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('titel', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('img', models.ImageField(default='default.png', upload_to='cource_img')),
            ],
            options={
                'verbose_name': 'Курсы',
                'verbose_name_plural': 'Курс',
            },
        ),
    ]
