# Generated by Django 3.1 on 2020-08-23 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0002_auto_20200822_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='cource',
            name='name',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cource',
            name='description',
            field=models.TextField(verbose_name='Описание курса'),
        ),
        migrations.AlterField(
            model_name='cource',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Имя курса'),
        ),
        migrations.AlterField(
            model_name='cource',
            name='titel',
            field=models.CharField(max_length=100, verbose_name='Заголовок курса'),
        ),
    ]
