# Generated by Django 3.1 on 2020-08-23 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200823_0657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cource',
            name='name',
        ),
    ]
